name: Run Preprocessing and Notebook

on:
  push:
    paths:
      - 'preprocessing/**'
  pull_request:
    paths:
      - 'preprocessing/**'

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9.21
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.21

    - name: Install dependencies
      run: |
        pip install pandas==2.2.2
        pip install numpy==1.26.4
        pip install scikit-learn==1.4.2
        pip install matplotlib==3.8.4
        pip install seaborn==0.13.2
        pip install notebook jupyter nbconvert

    - name: Run Python Script
      run: |
        python "preprocessing/automate_Muhammad Fawaid As'ad.py"

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute \
        "preprocessing/Eksperimen_Muhammad Fawaid As'ad.ipynb" \
        --output executed_notebook.ipynb

